name = "mirrorworkshop"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "B2_KV"

[[queues.producers]]
queue = "mirror-tasks"
binding = "TASKS_QUEUE"

[[queues.consumers]]
queue = "mirror-tasks"
max_batch_size = 1
max_retries = 3
max_concurrency = 1   # 新增：确保同一时间只处理一个批次任务